name: Promote Python Package

on:
  repository_dispatch:
    types: [package.synced]

permissions:
  id-token: write

env:
  CLOUDSMITH_NAMESPACE: ${{ vars.CLOUDSMITH_NAMESPACE }}
  CLOUDSMITH_STAGING_REPO: 'staging'
  CLOUDSMITH_PRODUCTION_REPO: 'production'
  CLOUDSMITH_SERVICE_SLUG: ${{ vars.CLOUDSMITH_SERVICE_SLUG }}

jobs:
  promote:
    runs-on: ubuntu-latest

    steps:
      - name: Install Cloudsmith CLI
        uses: cloudsmith-io/cloudsmith-cli-action@v1.0.1
        with:
          oidc-namespace: ${{ env.CLOUDSMITH_NAMESPACE }}
          oidc-service-slug: ${{ env.CLOUDSMITH_SERVICE_SLUG }}

      - name: Extract package identifier
        id: extract
        run: |
          IDENTIFIER="${{ github.event.client_payload.data.slug_perm }}"
          echo "Extracted package identifier: $IDENTIFIER"
          echo "identifier=$IDENTIFIER" >> $GITHUB_OUTPUT
        shell: bash

      - name: Tag package as ready-for-production
        run: |
          IDENTIFIER="${{ steps.extract.outputs.identifier }}"
          echo "Tagging package $IDENTIFIER with 'ready-for-production'"
          cloudsmith tags add \
            ${{ env.CLOUDSMITH_NAMESPACE }}/${{ env.CLOUDSMITH_STAGING_REPO }}/$IDENTIFIER \
            ready-for-production
        shell: bash

      - name: Promote package if tagged 'ready-for-production'
        run: |
          IDENTIFIER="${{ steps.extract.outputs.identifier }}"
          echo "Checking tags for package: $IDENTIFIER"

          TAGS=$(cloudsmith tags list ${{ env.CLOUDSMITH_NAMESPACE }}/${{ env.CLOUDSMITH_STAGING_REPO }}/$IDENTIFIER -F json)
          HAS_TAG=$(echo "$TAGS" | jq -r '.data[]?.slug' | grep -x "ready-for-production" || true)

          if [ -n "$HAS_TAG" ]; then
            echo "Promoting package: $IDENTIFIER"
            cloudsmith move \
              ${{ env.CLOUDSMITH_NAMESPACE }}/${{ env.CLOUDSMITH_STAGING_REPO }}/$IDENTIFIER \
              ${{ env.CLOUDSMITH_PRODUCTION_REPO }}
          else
            echo "Package $IDENTIFIER does not have 'ready-for-production' tag. Skipping promotion."
          fi
        shell: bash
