name: Promote Python Package

on:
  repository_dispatch:
    types: [package.synced]

permissions:
  id-token: write

env:
  CLOUDSMITH_NAMESPACE: ${{ vars.CLOUDSMITH_NAMESPACE }}
  CLOUDSMITH_STAGING_REPO: 'staging'
  CLOUDSMITH_PRODUCTION_REPO: 'production'
  CLOUDSMITH_SERVICE_SLUG: ${{ vars.CLOUDSMITH_SERVICE_SLUG }}

jobs:
  promote:
    runs-on: ubuntu-latest

    steps:
      - name: Install Cloudsmith CLI
        uses: cloudsmith-io/cloudsmith-cli-action@v1.0.1
        with:
          oidc-namespace: ${{ env.CLOUDSMITH_NAMESPACE }}
          oidc-service-slug: ${{ env.CLOUDSMITH_SERVICE_SLUG }}

      - name: Extract Package Identifier from Webhook Payload
        id: extract
        run: |
          echo "Payload: ${{ toJson(github.event.client_payload) }}"
          IDENTIFIER=$(echo '${{ toJson(github.event.client_payload.data.identifier_perm) }}' | tr -d '"')
          echo "identifier=$IDENTIFIER" >> $GITHUB_OUTPUT
        shell: bash

      - name: Tag package with ready-for-production
        run: |
          IDENTIFIER="${{ steps.extract.outputs.identifier }}"
          echo "Tagging package $IDENTIFIER with tag: ready-for-production"
          cloudsmith tags add --yes \
            ${{ env.CLOUDSMITH_NAMESPACE }}/${{ env.CLOUDSMITH_STAGING_REPO }}/$IDENTIFIER \
            ready-for-production
        shell: bash

      - name: Promote all ready-for-production tagged packages
        run: |
          echo "Looking for packages tagged ready-for-production..."

          PACKAGE_DATA=$(cloudsmith list package ${{ env.CLOUDSMITH_NAMESPACE }}/${{ env.CLOUDSMITH_STAGING_REPO }} -F json --tag "ready-for-production")
          COUNT=$(echo "$PACKAGE_DATA" | jq '.data | length')

          if [ "$COUNT" -eq 0 ]; then
            echo "No packages found with the ready-for-production tag."
            exit 0
          fi

          for IDENTIFIER in $(echo "$PACKAGE_DATA" | jq -r '.data[].identifier_perm'); do
            echo "Promoting package: $IDENTIFIER"
            cloudsmith mv --yes \
              ${{ env.CLOUDSMITH_NAMESPACE }}/${{ env.CLOUDSMITH_STAGING_REPO }}/$IDENTIFIER \
              ${{ env.CLOUDSMITH_PRODUCTION_REPO }}
          done
        shell: bash
