name: Promote Python Package

on:
  repository_dispatch:
    types: [package.synced]

permissions:
  id-token: write

env:
  CLOUDSMITH_NAMESPACE: ${{ vars.CLOUDSMITH_NAMESPACE }}
  CLOUDSMITH_STAGING_REPO: 'staging'
  CLOUDSMITH_PRODUCTION_REPO: 'production'
  CLOUDSMITH_SERVICE_SLUG: ${{ vars.CLOUDSMITH_SERVICE_SLUG }}

jobs:
  promote:
    runs-on: ubuntu-latest

    steps:
      - name: Install Cloudsmith CLI
        uses: cloudsmith-io/cloudsmith-cli-action@v1.0.1
        with:
          oidc-namespace: ${{ env.CLOUDSMITH_NAMESPACE }}
          oidc-service-slug: ${{ env.CLOUDSMITH_SERVICE_SLUG }}

      - name: Extract package identifier
        id: extract
        run: |
          IDENTIFIER="${{ github.event.client_payload.data.slug_perm }}"
          echo "Extracted package identifier: $IDENTIFIER"
          echo "identifier=$IDENTIFIER" >> $GITHUB_OUTPUT
        shell: bash

      - name: Tag package as ready-for-production
        run: |
          IDENTIFIER="${{ steps.extract.outputs.identifier }}"
          echo "Tagging package $IDENTIFIER with 'ready-for-production'"
          cloudsmith tags add \
            ${{ env.CLOUDSMITH_NAMESPACE }}/${{ env.CLOUDSMITH_STAGING_REPO }}/$IDENTIFIER \
            ready-for-production
        shell: bash

      - name: Promote packages tagged ready-for-production
        run: |
          echo "Looking for packages tagged 'ready-for-production' in staging..."
          
          PACKAGE_DATA=$(cloudsmith list package ${{ env.CLOUDSMITH_NAMESPACE }}/${{ env.CLOUDSMITH_STAGING_REPO }} -F json --tag "ready-for-production")
          COUNT=$(echo "$PACKAGE_DATA" | jq '.data | length')

          if [ "$COUNT" -eq 0 ]; then
            echo "No packages found with the 'ready-for-production' tag."
            exit 0
          fi

          for IDENTIFIER in $(echo "$PACKAGE_DATA" | jq -r '.data[].identifier_perm'); do
            echo "Promoting package: $IDENTIFIER"
            cloudsmith move \
              ${{ env.CLOUDSMITH_NAMESPACE }}/${{ env.CLOUDSMITH_STAGING_REPO }}/$IDENTIFIER \
              ${{ env.CLOUDSMITH_PRODUCTION_REPO }}
          done
        shell: bash
