name: Publish Python Package

on:
  workflow_run:
    workflows: ["Build Python Package"]
    types:
      - completed
    branches:
      - main

env:
  CLOUDSMITH_NAMESPACE: ${{ vars.CLOUDSMITH_NAMESPACE }}
  CLOUDSMITH_REPOSITORY: "staging"
  CLOUDSMITH_SERVICE_SLUG: ${{ vars.CLOUDSMITH_SERVICE_SLUG }}

permissions:
  contents: read
  actions: read
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: python-package
          path: dist
          repository: ${{ github.repository }}
          github-token: ${{ github.token }}
          run-id: ${{ github.event.workflow_run.id }}
      - name: Get OIDC token
        run: |
              echo "Fetching OIDC token..."
              
              # Step 1: Get the OIDC token from GitHub with custom audience
              value=$(curl -s -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
                "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=https://github.com/sonuverma1505/cloudsmith-cs-interview-candidate-sonu" | jq -r '.value')
              
              echo "Using OIDC token to authenticate with Cloudsmith..."
          
              # Step 2: Send OIDC token to Cloudsmith to get a short-lived API token
              token=$(curl -s -X POST https://api.cloudsmith.io/openid/interview-sonu-verma-vJXw/ \
                -H "Content-Type: application/json" \
                -d "{\"oidc_token\":\"$value\", \"service_slug\":\"test-git\"}" \
                | jq -r '.token')
          
              # Step 3: Optional - verify token works (get info on authenticated user)
              curl --request GET \
                --url https://api.cloudsmith.io/v1/user/self/ \
                --header "Authorization: Bearer $token" \
                --header "Accept: application/json"
          
              # Step 4: Export for later steps
              echo "CLOUDSMITH_API_KEY=$token" >> $GITHUB_ENV

      - name: Cloudsmith Push Pyhon Package    
        uses: cloudsmith-io/action@v0.5.3
        with:
            command: 'push'
            format: 'python'
            owner: 'interview-sonu-verma-vJXw'
            repo: 'staging'
            file: 'dist/*.tar.gz'
            republish: 'true'