name: Publish Python Package

on:
  workflow_run:
    workflows: ["Build Python Package"]
    types:
      - completed
    branches:
      - main

env:
  CLOUDSMITH_NAMESPACE: ${{ vars.CLOUDSMITH_NAMESPACE }}
  CLOUDSMITH_REPOSITORY: "staging"
  CLOUDSMITH_SERVICE_SLUG: ${{ vars.CLOUDSMITH_SERVICE_SLUG }}

permissions:
  contents: read
  actions: read
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: python-package
          path: dist
          repository: ${{ github.repository }}
          github-token: ${{ github.token }}
          run-id: ${{ github.event.workflow_run.id }}
      - name: Get OIDC token
        run: |
          echo "Fetching OIDC token..."
          value=$(curl -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=api://AzureADTokenExchange" | jq -r '.value')
          echo "Using OIDC token for Cloudsmith API..."
          token=$(curl -X POST -H "Content-Type: application/json" -d "{\"oidc_token\":$value, \"service_slug\":\test-git\"}" https://api.cloudsmith.io/openid/interview-sonu-verma-vJXw/ | jq -r '.token')
          curl --request GET --url https://api.cloudsmith.io/v1/user/self/ --header "X-Api-Key:Bearer $token" --header 'accept: application/json'
        
          echo "CLOUDSMITH_API_KEY=$token" >> $GITHUB_ENV
      - name: Push Python package to Cloudsmith
        uses: cloudsmith-io/action@v0.5.3
        with:
          command: 'push'
          format: 'python'
          owner: ${{ env.CLOUDSMITH_NAMESPACE }}
          repo: ${{ env.CLOUDSMITH_REPOSITORY }}
          file: 'dist/*.tar.gz'
          republish: 'true'